# Generated by Django 4.1.7 on 2023-03-01 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='Summary')),
                ('description', models.TextField(max_length=3000, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Time updated')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='tracker.status')),
                ('type', models.ManyToManyField(blank=True, null=True, related_name='tasks', to='tracker.type')),
            ],
        ),
    ]
