# Generated by Django 4.1.7 on 2023-03-02 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='Summary')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Time updated')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issues', to='tracker.status')),
                ('type', models.ManyToManyField(blank=True, related_name='issues', to='tracker.type')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
