# Generated by Django 4.1.7 on 2023-03-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_issue_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Deletion time'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
